name: PR Review Label

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

  schedule:
    - cron: '*/15 * * * *'  # 每15分钟检查一次

jobs:
  label-management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Add Initial Review Label
        if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "action:review"

  review-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check Reviews and Update Label
        run: |
          prs=$(gh pr list --state open --json number)
          for pr in $(echo "${prs}" | jq -r '.[].number'); do
            reviews=$(gh pr review list $pr --json state)
            approved_count=$(echo "$reviews" | jq '[.[] | select(.state == "APPROVED")] | length')
            if [ "$approved_count" -ge 2 ]; then
              gh pr edit $pr --add-label "action:merge"
            fi
          done
